DROP INDEX IF EXISTS idx_room_users_active_listener_room_last_seen_at;
DROP INDEX IF EXISTS idx_songs_duplicate_guard;

ALTER TABLE room_settings
ALTER COLUMN skip_allowed DROP DEFAULT,
ALTER COLUMN skip_allowed TYPE BOOLEAN USING skip_allowed = 1,
ALTER COLUMN skip_allowed SET DEFAULT TRUE,
ALTER COLUMN democratic_skip DROP DEFAULT,
ALTER COLUMN democratic_skip TYPE BOOLEAN USING democratic_skip = 1,
ALTER COLUMN democratic_skip SET DEFAULT TRUE,
ALTER COLUMN remove_on_play DROP DEFAULT,
ALTER COLUMN remove_on_play TYPE BOOLEAN USING remove_on_play = 1,
ALTER COLUMN remove_on_play SET DEFAULT TRUE,
ALTER COLUMN loop_queue DROP DEFAULT,
ALTER COLUMN loop_queue TYPE BOOLEAN USING loop_queue = 1,
ALTER COLUMN loop_queue SET DEFAULT FALSE,
ALTER COLUMN allow_duplicates DROP DEFAULT,
ALTER COLUMN allow_duplicates TYPE BOOLEAN USING allow_duplicates = 1,
ALTER COLUMN allow_duplicates SET DEFAULT FALSE,
ALTER COLUMN only_admin_add_songs DROP DEFAULT,
ALTER COLUMN only_admin_add_songs TYPE BOOLEAN USING only_admin_add_songs = 1,
ALTER COLUMN only_admin_add_songs SET DEFAULT FALSE;

ALTER TABLE playback_state
ALTER COLUMN is_playing DROP DEFAULT,
ALTER COLUMN is_playing TYPE BOOLEAN USING is_playing = 1,
ALTER COLUMN is_playing SET DEFAULT FALSE;

ALTER TABLE room_users
ALTER COLUMN is_admin DROP DEFAULT,
ALTER COLUMN is_admin TYPE BOOLEAN USING is_admin = 1,
ALTER COLUMN is_admin SET DEFAULT FALSE,
ALTER COLUMN is_active_listener DROP DEFAULT,
ALTER COLUMN is_active_listener TYPE BOOLEAN USING is_active_listener = 1,
ALTER COLUMN is_active_listener SET DEFAULT FALSE,
ALTER COLUMN is_cast_receiver DROP DEFAULT,
ALTER COLUMN is_cast_receiver TYPE BOOLEAN USING is_cast_receiver = 1,
ALTER COLUMN is_cast_receiver SET DEFAULT FALSE;

ALTER TABLE songs
ALTER COLUMN duplicate_guard DROP DEFAULT,
ALTER COLUMN duplicate_guard TYPE BOOLEAN USING duplicate_guard = 1,
ALTER COLUMN duplicate_guard SET DEFAULT TRUE;

ALTER TABLE rooms
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE songs
ALTER COLUMN added_at DROP DEFAULT,
ALTER COLUMN added_at TYPE TIMESTAMP USING added_at AT TIME ZONE 'UTC',
ALTER COLUMN added_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE playback_state
ALTER COLUMN updated_at DROP DEFAULT,
ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE room_users
ALTER COLUMN joined_at DROP DEFAULT,
ALTER COLUMN joined_at TYPE TIMESTAMP USING joined_at AT TIME ZONE 'UTC',
ALTER COLUMN joined_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
ALTER COLUMN last_seen_at DROP DEFAULT,
ALTER COLUMN last_seen_at TYPE TIMESTAMP USING last_seen_at AT TIME ZONE 'UTC',
ALTER COLUMN last_seen_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE skip_votes
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE song_votes
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE auth_tokens
ALTER COLUMN expires_at TYPE TIMESTAMP USING expires_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
ALTER COLUMN updated_at DROP DEFAULT,
ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE access_tokens
ALTER COLUMN expires_at TYPE TIMESTAMP USING expires_at AT TIME ZONE 'UTC',
ALTER COLUMN refresh_expires_at TYPE TIMESTAMP USING refresh_expires_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
ALTER COLUMN updated_at DROP DEFAULT,
ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
ALTER COLUMN last_checked TYPE TIMESTAMP USING last_checked AT TIME ZONE 'UTC';

ALTER TABLE pending_oauth_state
ALTER COLUMN expires_at TYPE TIMESTAMP USING expires_at AT TIME ZONE 'UTC';

CREATE UNIQUE INDEX IF NOT EXISTS idx_songs_duplicate_guard
ON songs(room_id, source_type, source_id)
WHERE duplicate_guard;

CREATE INDEX IF NOT EXISTS idx_room_users_active_listener_room_last_seen_at
ON room_users(room_id, last_seen_at)
WHERE is_active_listener
AND NOT is_cast_receiver;
