CREATE TABLE search_usage_hourly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    query_hash TEXT NOT NULL,
    cached BOOLEAN NOT NULL,
    search_count BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT DATE_TRUNC('hour', NOW())
);

INSERT INTO search_usage_hourly (
    provider,
    query_hash,
    cached,
    search_count,
    created_at
)
SELECT
    provider,
    query_hash,
    cached,
    COUNT(*),
    DATE_TRUNC('hour', created_at)
FROM search_usage
WHERE created_at >= NOW() - INTERVAL '32 days'
GROUP BY
    provider,
    query_hash,
    cached,
    DATE_TRUNC('hour', created_at);

DROP TABLE search_usage;

ALTER TABLE search_usage_hourly
RENAME TO search_usage;

CREATE UNIQUE INDEX idx_search_usage_hourly
ON search_usage (provider, query_hash, cached, created_at);

CREATE INDEX idx_search_usage_created_at
ON search_usage (created_at);
