CREATE TABLE search_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    query_hash TEXT NOT NULL,
    cached BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO search_usage_events (
    provider,
    query_hash,
    cached,
    created_at
)
SELECT
    a.provider,
    a.query_hash,
    a.cached,
    a.created_at
FROM search_usage a
CROSS JOIN LATERAL GENERATE_SERIES(1, a.search_count);

DROP TABLE search_usage;

ALTER TABLE search_usage_events
RENAME TO search_usage;

CREATE INDEX idx_search_usage_created_at
ON search_usage (created_at);
