package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func main() {
	var databaseURL string
	var down bool
	var steps int
	command := "up"

	if len(os.Args) > 1 {
		if os.Args[1] == "up" || os.Args[1] == "down" {
			command = os.Args[1]
			os.Args = append([]string{os.Args[0]}, os.Args[2:]...)
		}
	}

	flag.StringVar(&databaseURL, "db", os.Getenv("DATABASE_URL"), "Postgres connection URL")
	flag.BoolVar(&down, "down", false, "Run down migrations")
	flag.IntVar(&steps, "steps", 0, "Number of steps to migrate (0 for all)")
	flag.Parse()

	if databaseURL == "" {
		log.Fatal("DATABASE_URL or -db is required")
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		log.Fatalf("Failed to open database: %v", err)
	}
	defer db.Close()

	if err := ensureMigrationTable(db); err != nil {
		log.Fatalf("Failed to ensure migration table: %v", err)
	}

	if command == "down" {
		down = true
	}

	err = runMigrations(db, down, steps)
	if err != nil {
		log.Fatalf("Migration failed: %v", err)
	}

	log.Println("Migrations completed successfully")
}

func ensureMigrationTable(db *sql.DB) error {
	query := `
	CREATE TABLE IF NOT EXISTS migrations (
		id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		version INTEGER NOT NULL,
		dirty BOOLEAN NOT NULL DEFAULT FALSE,
		applied_at TIMESTAMPTZ DEFAULT NOW()
	);
	`
	_, err := db.Exec(query)
	return err
}

func runMigrations(db *sql.DB, down bool, steps int) error {
	currentVersion, dirty, err := getCurrentVersion(db)
	if err != nil {
		return fmt.Errorf("getting current version: %w", err)
	}

	log.Printf("Current version: %d (dirty: %v)", currentVersion, dirty)

	if dirty {
		return fmt.Errorf("database is in a dirty state (version %d). Fix manually", currentVersion)
	}

	files, err := getMigrationFiles()
	if err != nil {
		return fmt.Errorf("getting migration files: %w", err)
	}

	if down {
		log.Println("Running down migrations...")
		return applyDownMigrations(db, currentVersion, steps, files)
	}
	log.Println("Running up migrations...")
	return applyUpMigrations(db, currentVersion, steps, files)
}

func getCurrentVersion(db *sql.DB) (int, bool, error) {
	var version int
	var dirty bool
	row := db.QueryRow("SELECT version, dirty FROM migrations ORDER BY id DESC LIMIT 1")
	err := row.Scan(&version, &dirty)
	if err == sql.ErrNoRows {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	return version, dirty, nil
}

func getMigrationFiles() ([]string, error) {
	paths := []string{"./migrations"}
	var dir string
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			dir = p
			break
		}
	}
	if dir == "" {
		// Log current working directory and what we tried
		cwd, _ := os.Getwd()
		log.Printf("Current working directory: %s", cwd)
		log.Printf("Tried paths: %v", paths)
		return nil, fmt.Errorf("migrations directory not found in %v", paths)
	}

	log.Printf("Using migrations directory: %s", dir)
	files, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("error reading migrations directory: %w", err)
	}

	var migrationFiles []string
	for _, f := range files {
		if f.IsDir() {
			continue
		}
		// Format: 0001_initial_schema.up.sql
		parts := strings.SplitN(f.Name(), "_", 2)
		if len(parts) < 2 {
			continue
		}
		if _, err := strconv.Atoi(parts[0]); err != nil {
			continue
		}
		migrationFiles = append(migrationFiles, filepath.Join(dir, f.Name()))
	}

	log.Printf("Found %d migration files", len(migrationFiles))
	return migrationFiles, nil
}

func applyUpMigrations(db *sql.DB, currentVersion int, steps int, files []string) error {
	var versions []int
	// We need to parse all up files
	upFiles := make(map[int]string)

	for _, path := range files {
		if strings.HasSuffix(path, ".up.sql") {
			base := filepath.Base(path)
			parts := strings.SplitN(base, "_", 2)
			v, _ := strconv.Atoi(parts[0])
			upFiles[v] = path
			versions = append(versions, v)
		}
	}
	sort.Ints(versions)

	count := 0
	for _, v := range versions {
		if v <= currentVersion {
			continue
		}
		if steps > 0 && count >= steps {
			break
		}

		log.Printf("Migrating to version: %d", v)
		log.Printf("Applying migration %d...", v)
		if err := setDirty(db, v, true); err != nil {
			return err
		}

		content, err := os.ReadFile(upFiles[v])
		if err != nil {
			return err
		}

		if _, err := db.Exec(string(content)); err != nil {
			return fmt.Errorf("executing migration %d: %w", v, err)
		}

		if err := setDirty(db, v, false); err != nil {
			return err
		}
		count++
	}
	return nil
}

func applyDownMigrations(db *sql.DB, currentVersion int, steps int, files []string) error {
	if currentVersion == 0 {
		return nil
	}

	// Find down files
	downFiles := make(map[int]string)
	for _, path := range files {
		if strings.HasSuffix(path, ".down.sql") {
			base := filepath.Base(path)
			parts := strings.SplitN(base, "_", 2)
			v, _ := strconv.Atoi(parts[0])
			downFiles[v] = path
		}
	}

	count := 0
	// We reverse loop from current version downwards
	// If current is 2, we want to run down for 2, then set version to 1.
	// If we want 1 step, we run down 2, set version 1.
	// If we want to go down to 0, we run down 2 (v=1), down 1 (v=0).

	// We don't have a list of versions to iterate easily unless we reconstruct it.
	// We can just loop backwards from currentVersion.

	for v := currentVersion; v > 0; v-- {
		if steps > 0 && count >= steps {
			break
		}

		path, ok := downFiles[v]
		if !ok {
			return fmt.Errorf("down migration file not found for version %d", v)
		}

		log.Printf("Reverting migration %d to version %d...", v, v-1)
		if err := setDirty(db, v, true); err != nil {
			return err
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		if _, err := db.Exec(string(content)); err != nil {
			return fmt.Errorf("executing down migration %d: %w", v, err)
		}

		// After down migration V, the new version is V-1.
		// We record that migration V is no longer applied.
		// The table stores history, so we insert a new row with version V-1 and dirty=false.
		if err := setDirty(db, v-1, false); err != nil {
			return err
		}
		count++
	}
	return nil
}

func setDirty(db *sql.DB, version int, dirty bool) error {
	_, err := db.Exec("INSERT INTO migrations (version, dirty) VALUES ($1, $2)", version, dirty)
	return err
}
